require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "bin/*"
    - "tmp/**/*"
    - "db/schema.rb"

Layout/LineLength:
  Max: 120

# TODO: Enable this
Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

# New rules to opt-in after v0.80
# Cf: https://docs.rubocop.org/en/latest/versioning/

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true