# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

defaults: &defaults
  docker:
    - image: circleci/ruby:2.7.2-browsers
    - image: circleci/postgres:11.5
      environment:
        POSTGRES_DB: moss-back-test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

bundle_restore_cache: &bundle_restore_cache
  restore_cache:
    key: v1-bundle-install-{{ arch }}-{{ checksum "Gemfile.lock" }}

bundle_save_cache: &bundle_save_cache
  save_cache:
    key: v1-bundle-install-{{ arch }}-{{ checksum "Gemfile.lock" }}
    paths:
      - ~/vendor/bundle

bundle_install: &bundle_install
  run:
    name: Install Ruby Dependencies
    command: bundle install --path ~/vendor/bundle

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *bundle_restore_cache
      - *bundle_install
      - *bundle_save_cache
  test:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - *bundle_restore_cache
      - *bundle_install
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          environment:
            DATABASE_URL: "postgres://postgres:postgres@localhost:5432/moss-back-test"
          name: Create DB
          command: bundle exec rails db:create db:schema:load db:migrate RAILS_ENV=test
      - run:
          environment:
            FRONT_BASE_URL: http://moss-front
            APPLICATION_EMAIL_ADDRESS: testemail@octo.com
            SECRET_KEY_BASE: 4e9d18683db85ddb440df081dc1aae1d
            DATABASE_URL: "postgres://postgres:postgres@localhost:5432/moss-back-test"
          name: Run Tests, Split by Timings
          command: |
            bundle exec rspec --profile 10 \
              --format RspecJunitFormatter \
              --out ~/test-results/rspec/results.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: ~/test-results
  lint:
    <<: *defaults
    steps:
      - checkout
      - *bundle_restore_cache
      - *bundle_install
      - run:
          name: Run lint tasks
          command: bundle exec rubocop

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
